version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    environment:
      APP_ENV: production
      APP_KEY: base64:a98G/IsVlQr8FH3gtGT1qOyhPNNvPgitGhhLTTx9iZg=
      APP_DEBUG: false
      DB_CONNECTION: mongodb
      DB_HOST: 
      DB_DATABASE: pharmacy
      DB_URI: mongodb+srv://mongodb:mongodb@pharmacy.qy1rs.mongodb.net/pharmacy?retryWrites=true&w=majority
